### ISSUE TITLE
Could not render cell - The data to decrypt cannot be empty.

### ISSUE THREAD

**Issue by danfournier** [adayth/cakephp-cipher-behavior#3]
We're getting the following error:

`Warning (512): Could not render cell - The data to decrypt cannot be empty. [C:\wamp\myapp\vendor\cakephp\cakephp\src\Utility\Security.php, line 265] [CORE\src\View\Cell.php, line 271]`

We're using this plugin along side an audit plugin. The plugin, when initially creating a record, will also create an audit entry where the "original" field value will be null. I'm assuming this is what's causing the issue?

**Comment by adayth** [comment]
Can you give me the steps, configuration, plugins, to be able to replicate the issue?

You are right, the plugin could have issues if your encrypted column data is empty. This could happen writing and reading to database.

**Comment by danfournier** [comment]
I will try to get a smaller test case ready that I can share.

In the meantime, I essentially used the [AuditStash](https://github.com/lorenzo/audit-stash) plugin for auditing. I used the custom persister using the code specified in [this issue](https://github.com/lorenzo/audit-stash/issues/14). I changed the columns _original_ and _changed_ to type BLOB. I also added encryption on the _original_ and _changed_ columns from that example.

**Comment by adayth** [comment]
You could try to modify or debug beforeFind method in the behaviour to test what is happening. 

I suggest to modify line 130 in CipherBehavior  class to:

```php
if ($entity->has($field) && $entity->get($field)) {
````
With that check the behaviour will never try to decrypt an empty value.

**Comment by danfournier** [comment]
That seems to work.

**Comment by adayth** [comment]
Nice! You could do a copy of the behaviour class to your app folder and do the modifications there.
